[tool.poetry]
name = "qlearner-snake-python"
version = "1.0.0"
description = "A simple QLearner Battlesnake written in Python"
authors = ["Pi-Ching Liu <pichingliu@google.com>", "Yao-Sheng Tsa <yaoshen@google.com>"]

[tool.poetry.dependencies]
python = "^3.8"
cherrypy = "^18.6"
numpy = "^1.20.3"
